name: Deploy Gatsby to Azure Storage

on:   
 push:  
   branches:  
     - main

jobs:  
 build:

   runs-on: self-hosted

   strategy:  
     matrix:  
       node-version: [18.x]
   steps:  
   - uses: actions/checkout@v1  
       
   - name: Use Node.js ${{ matrix.node-version }}  
     uses: actions/setup-node@v1  
     with:  
       node-version: ${{ matrix.node-version }}  
   
   - name: Install dependencies  
     run: |  
       npm install --legacy-peer-deps
       npm install -g gatsby-cli 
   - name: Build with Gatsby  
     run: gatsby build
         
   - name: Azure upload  
     uses: azure/CLI@v1  
     with:  
       azcliversion: 2.0.72  
       inlineScript: |  
         az storage blob delete-batch -s "\$web" --connection-string "${{ secrets.CONNECTION_STRING }}"  
         az storage blob upload-batch -d "\$web" -s public --connection-string "${{ secrets.CONNECTION_STRING }}"
 backup:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Backup Azure Blob Storage
        uses: azure/powershell@v1
        with:
           inlineScript: |
              $connectionString = "DefaultEndpointsProtocol=https;AccountName=qfstw;AccountKey=vf4+0aIJGxZaRZU1TZybA3/kh5k9TFl7PykvitfUnDKJRbUGFL9hSbIIRHBAfYKb6CS7T2XJd4CF+ASt9B16eg==;EndpointSuffix=core.windows.net"
              $tenantId = "f480c097-c9ad-49e3-bd75-963178917aa1"
              $clientID = "60b58dbb-4f8b-4dfd-b763-e4f9df141925"
              $clientSecret = "z__8Q~3ZRhG7HLMwyM6wkW3JSe1EH3QsQtW.0ato"
              $subscriptionId = "c3dff2a8-ba98-4189-94a7-d3a42bfc42cd"
              $storageAccountKey="vf4+0aIJGxZaRZU1TZybA3/kh5k9TFl7PykvitfUnDKJRbUGFL9hSbIIRHBAfYKb6CS7T2XJd4CF+ASt9B16eg=="
              $securePassword = ConvertTo-SecureString $clientSecret -AsPlainText -Force
              $psCredential = New-Object System.Management.Automation.PSCredential($clientID,$securePassword)
              Connect-AzAccount -ServicePrincipal -Credential $psCredential -TenantId $tenantId -SubscriptionId $subscriptionId
              $storageAccount = Get-AzStorageAccount -ResourceGroupName "QF-SWA" -Name "qfstw"
              $storageContext = New-AzStorageContext -StorageAccountName $storageAccount.StorageAccountName -StorageAccountKey $storageAccountKey
              $web = '$web'
              $sourceBlobList = Get-AzStorageBlob -Container $web -Context $storageContext
              $destinationContainerName = "backup-" + (Get-Date).ToString("yyyyMMddHHmmss")
              New-AzStorageContainer -Name $destinationContainerName -Context $storageContext
              $destinationContext = New-AzStorageContext -ConnectionString $connectionString
              foreach ($blob in $sourceBlobList) {
                 $destinationBlobName = $blob.Name
                 $destinationBlob = Start-AzStorageBlobCopy -Context $destinationContext -SrcContainer $web -SrcBlob $blob.Name -DestContainer $destinationContainerName -DestBlob $destinationBlobName -Force -BlobType BlockBlob
              }
           azPSVersion: "latest"
