name: Deploy Gatsby to Azure Storage

on:   
 push:  
   branches:  
     - main

jobs:  
 build:

   runs-on: self-hosted

   strategy:  
     matrix:  
       node-version: [18.x]

   steps:  
         
   - name: Build with Gatsby  
     run: gatsby build  
     
   - name: Azure upload  
     uses: azure/CLI@v1  
     with:  
       azcliversion: 2.0.72  
       inlineScript: |  
         az storage blob delete-batch -s "\$web" --connection-string "${{ secrets.CONNECTION_STRING }}"  
         az storage blob upload-batch -d "\$web" -s public --connection-string "${{ secrets.CONNECTION_STRING }}"  
