name: Azure Blob Storage Backup

on:
  push:
    branches: main

jobs:
  backup:
    runs-on: windows-latest

    steps:

      - name: Backup Azure Blob Storage
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $web = '$web'
            $connectionString = Get-AzStorageAccount -ResourceGroupName QF-SWA -Name qfstw | Get-AzStorageAccountKey -KeyName key1 | Select-Object -ExpandProperty Value
            $sourceContext = New-AzStorageContext -ConnectionString $connectionString
            $sourceBlobList = Get-AzStorageBlob -Container $web -Context $sourceContext
            $destinationContainerName = "backup-" + (Get-Date).ToString("yyyyMMddHHmmss")
            New-AzStorageContainer -Name $destinationContainerName -Context $sourceContext
            $destinationContext = New-AzStorageContext -ConnectionString $connectionString
            foreach ($blob in $sourceBlobList) {
                $destinationBlobName = $blob.Name
                $destinationBlob = Start-AzStorageBlobCopy -Context $destinationContext -SrcContainer $web -SrcBlob $blob.Name -DestContainer $destinationContainerName -DestBlob $destinationBlobName -Force
            }
          azPSVersion: "latest"
