name: Azure Blob Storage Backup

on:
  push:
    branches: main

jobs:
  backup:
    runs-on: windows-latest

    steps:

      - name: Backup Azure Blob Storage
        uses: azure/powershell@v1
        with:
           inlineScript: |
             $connectionString = "DefaultEndpointsProtocol=https;AccountName=qfstw;AccountKey=vf4+0aIJGxZaRZU1TZybA3/kh5k9TFl7PykvitfUnDKJRbUGFL9hSbIIRHBAfYKb6CS7T2XJd4CF+ASt9B16eg==;EndpointSuffix=core.windows.net"
             $context = New-AzStorageContext -ConnectionString $connectionString
             Get-AzStorageAccount -ResourceGroupName QF-SWA -Name qfstw
             azPSVersion: "latest"
             $web = '$web'
             $sourceContext = New-AzStorageContext -ConnectionString $connectionString
             $sourceBlobList = Get-AzStorageBlob -Container $web -Context $sourceContext

             $destinationContainerName = "backup-" + (Get-Date).ToString("yyyyMMddHHmmss")
             New-AzStorageContainer -Name $destinationContainerName -Context $sourceContext
             $destinationContext = New-AzStorageContext -ConnectionString $connectionString
             foreach ($blob in $sourceBlobList) {
                $destinationBlobName = $blob.Name
                $destinationBlob = Start-AzStorageBlobCopy -Context $destinationContext -SrcContainer $web -SrcBlob $blob.Name -DestContainer $destinationContainerName -DestBlob $destinationBlobName -Force
                }
              azPSVersion: "latest"
